name: technocare
description: "Sizin mühəndislik həlliniz"
publish_to: 'none'
version: "2.1.2+17"

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  flutter_local_notifications: ^22.3.0
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.2.4
  google_nav_bar: ^5.0.7
  http: ^1.1.0
  intl: ^0.20.2
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/technocare.png
    - assets/images/content/
    - assets/images/projects/
    - assets/icons/app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
